version: '3.7'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    environment:
      - CADDY_INGRESS_NETWORKS=moodle
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - $PWD/.docker/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - moodle
  db:
    image: mysql:8.0
    container_name: moodle-db
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '33060:3306'
    environment:
      MYSQL_ROOT_PASSWORD: moodle
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    networks:
      - moodle
  moodle:
    depends_on:
      - db
    build:
      context: ./.docker
      dockerfile: php-apache/Dockerfile
    image: moodle:latest
    container_name: moodle
    volumes:
      - $PWD/src:/var/www/html
      - $PWD/.docker/php-apache/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - $PWD/.docker/php-apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    labels:
      caddy: moodle.localhost
      caddy.reverse_proxy: '{{upstreams 80}}'
      caddy.tls: 'internal'
    networks:
      - moodle
volumes:
  mysql-data: {}
  caddy_data: {}
  caddy_config: {}
networks:
  moodle:
    external: true
    name: moodle
